[tool.poetry]
name = "kyrie"
version = "0.1.0"
description = ""
authors = ["misut <pkr5207@gmail.com>"]
license = "MIT"
packages = [
    {include = "kyrie", from = "src"}
]


[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.4"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
isort = "^5.12.0"
mypy = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
